# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1724, 1314)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        MainWindow.setFont(font)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labelState = QtGui.QLabel(self.centralwidget)
        self.labelState.setObjectName(_fromUtf8("labelState"))
        self.verticalLayout_4.addWidget(self.labelState)
        self.textOutput = QtGui.QTextEdit(self.centralwidget)
        self.textOutput.setReadOnly(True)
        self.textOutput.setObjectName(_fromUtf8("textOutput"))
        self.verticalLayout_4.addWidget(self.textOutput)
        self.lineCmd = QtGui.QLineEdit(self.centralwidget)
        self.lineCmd.setObjectName(_fromUtf8("lineCmd"))
        self.verticalLayout_4.addWidget(self.lineCmd)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1724, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_2 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.treeMemory = QtGui.QTreeWidget(self.dockWidgetContents_2)
        self.treeMemory.setObjectName(_fromUtf8("treeMemory"))
        self.treeMemory.header().setCascadingSectionResizes(True)
        self.verticalLayout_2.addWidget(self.treeMemory)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_2)
        self.dockWidget_3 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_3.setObjectName(_fromUtf8("dockWidget_3"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.dockWidgetContents_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.LabelRole, self.label_16)
        self.lineX0 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX0.setObjectName(_fromUtf8("lineX0"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineX0)
        self.lineX2 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX2.setObjectName(_fromUtf8("lineX2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineX2)
        self.lineX4 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX4.setObjectName(_fromUtf8("lineX4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineX4)
        self.lineX6 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX6.setObjectName(_fromUtf8("lineX6"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineX6)
        self.lineX8 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX8.setObjectName(_fromUtf8("lineX8"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineX8)
        self.lineX10 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX10.setObjectName(_fromUtf8("lineX10"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineX10)
        self.lineX12 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX12.setObjectName(_fromUtf8("lineX12"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineX12)
        self.lineX14 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX14.setObjectName(_fromUtf8("lineX14"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineX14)
        self.lineX16 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX16.setObjectName(_fromUtf8("lineX16"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineX16)
        self.lineX18 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX18.setObjectName(_fromUtf8("lineX18"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineX18)
        self.lineX20 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX20.setObjectName(_fromUtf8("lineX20"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.lineX20)
        self.lineX22 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX22.setObjectName(_fromUtf8("lineX22"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.lineX22)
        self.lineX24 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX24.setObjectName(_fromUtf8("lineX24"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.lineX24)
        self.lineX26 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX26.setObjectName(_fromUtf8("lineX26"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.lineX26)
        self.lineX28 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX28.setObjectName(_fromUtf8("lineX28"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.lineX28)
        self.lineX30 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX30.setObjectName(_fromUtf8("lineX30"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.lineX30)
        self.label_33 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.LabelRole, self.label_33)
        self.lineSP = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineSP.setObjectName(_fromUtf8("lineSP"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.FieldRole, self.lineSP)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_17 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_22)
        self.label_23 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_23)
        self.label_24 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_24)
        self.label_25 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_27)
        self.label_28 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_28)
        self.label_29 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_29)
        self.label_30 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.formLayout_2.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_30)
        self.label_31 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout_2.setWidget(14, QtGui.QFormLayout.LabelRole, self.label_31)
        self.label_32 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_2.setWidget(15, QtGui.QFormLayout.LabelRole, self.label_32)
        self.lineX1 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX1.setObjectName(_fromUtf8("lineX1"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineX1)
        self.lineX3 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX3.setObjectName(_fromUtf8("lineX3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineX3)
        self.lineX5 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX5.setObjectName(_fromUtf8("lineX5"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineX5)
        self.lineX7 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX7.setObjectName(_fromUtf8("lineX7"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineX7)
        self.lineX9 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX9.setObjectName(_fromUtf8("lineX9"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineX9)
        self.lineX11 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX11.setObjectName(_fromUtf8("lineX11"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineX11)
        self.lineX13 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX13.setObjectName(_fromUtf8("lineX13"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineX13)
        self.lineX15 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX15.setObjectName(_fromUtf8("lineX15"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineX15)
        self.lineX17 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX17.setObjectName(_fromUtf8("lineX17"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineX17)
        self.lineX19 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX19.setObjectName(_fromUtf8("lineX19"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineX19)
        self.lineX21 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX21.setObjectName(_fromUtf8("lineX21"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.FieldRole, self.lineX21)
        self.lineX23 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX23.setObjectName(_fromUtf8("lineX23"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.FieldRole, self.lineX23)
        self.lineX25 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX25.setObjectName(_fromUtf8("lineX25"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.FieldRole, self.lineX25)
        self.lineX27 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX27.setObjectName(_fromUtf8("lineX27"))
        self.formLayout_2.setWidget(13, QtGui.QFormLayout.FieldRole, self.lineX27)
        self.lineX29 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineX29.setObjectName(_fromUtf8("lineX29"))
        self.formLayout_2.setWidget(14, QtGui.QFormLayout.FieldRole, self.lineX29)
        self.linePC = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.linePC.setObjectName(_fromUtf8("linePC"))
        self.formLayout_2.setWidget(15, QtGui.QFormLayout.FieldRole, self.linePC)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_3)
        self.dockWidget_4 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_4.setObjectName(_fromUtf8("dockWidget_4"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.treeThreads = QtGui.QTreeWidget(self.dockWidgetContents_4)
        self.treeThreads.setObjectName(_fromUtf8("treeThreads"))
        self.verticalLayout_5.addWidget(self.treeThreads)
        self.dockWidget_4.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_4)
        self.dockWidget_5 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_5.setObjectName(_fromUtf8("dockWidget_5"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.treeBreakpoints = QtGui.QTreeWidget(self.dockWidgetContents_5)
        self.treeBreakpoints.setObjectName(_fromUtf8("treeBreakpoints"))
        self.treeBreakpoints.headerItem().setText(1, _fromUtf8("Type"))
        self.verticalLayout_6.addWidget(self.treeBreakpoints)
        self.dockWidget_5.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_5)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeStackTrace = QtGui.QTreeWidget(self.dockWidgetContents)
        self.treeStackTrace.setObjectName(_fromUtf8("treeStackTrace"))
        self.treeStackTrace.headerItem().setText(0, _fromUtf8("1"))
        self.treeStackTrace.header().setVisible(False)
        self.verticalLayout.addWidget(self.treeStackTrace)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.dockWidget_6 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_6.setObjectName(_fromUtf8("dockWidget_6"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.dockWidgetContents_6)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.lineCmdView0 = QtGui.QLineEdit(self.dockWidgetContents_6)
        self.lineCmdView0.setObjectName(_fromUtf8("lineCmdView0"))
        self.verticalLayout_7.addWidget(self.lineCmdView0)
        self.textOutputView0 = QtGui.QTextEdit(self.dockWidgetContents_6)
        self.textOutputView0.setObjectName(_fromUtf8("textOutputView0"))
        self.verticalLayout_7.addWidget(self.textOutputView0)
        self.dockWidget_6.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_6)
        self.dockWidget_7 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_7.setObjectName(_fromUtf8("dockWidget_7"))
        self.dockWidgetContents_7 = QtGui.QWidget()
        self.dockWidgetContents_7.setObjectName(_fromUtf8("dockWidgetContents_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.dockWidgetContents_7)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.lineCmdView1 = QtGui.QLineEdit(self.dockWidgetContents_7)
        self.lineCmdView1.setObjectName(_fromUtf8("lineCmdView1"))
        self.verticalLayout_8.addWidget(self.lineCmdView1)
        self.textOutputView1 = QtGui.QTextEdit(self.dockWidgetContents_7)
        self.textOutputView1.setObjectName(_fromUtf8("textOutputView1"))
        self.verticalLayout_8.addWidget(self.textOutputView1)
        self.dockWidget_7.setWidget(self.dockWidgetContents_7)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_7)
        self.dockWidget_8 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_8.setObjectName(_fromUtf8("dockWidget_8"))
        self.dockWidgetContents_8 = QtGui.QWidget()
        self.dockWidgetContents_8.setObjectName(_fromUtf8("dockWidgetContents_8"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.dockWidgetContents_8)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.lineCmdView2 = QtGui.QLineEdit(self.dockWidgetContents_8)
        self.lineCmdView2.setObjectName(_fromUtf8("lineCmdView2"))
        self.verticalLayout_9.addWidget(self.lineCmdView2)
        self.textOutputView2 = QtGui.QTextEdit(self.dockWidgetContents_8)
        self.textOutputView2.setObjectName(_fromUtf8("textOutputView2"))
        self.verticalLayout_9.addWidget(self.textOutputView2)
        self.dockWidget_8.setWidget(self.dockWidgetContents_8)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_8)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "nxdbg", None))
        self.labelState.setText(_translate("MainWindow", "None", None))
        self.dockWidget_2.setWindowTitle(_translate("MainWindow", "Memory Layout", None))
        self.treeMemory.headerItem().setText(0, _translate("MainWindow", "Address", None))
        self.treeMemory.headerItem().setText(1, _translate("MainWindow", "Size", None))
        self.treeMemory.headerItem().setText(2, _translate("MainWindow", "Type", None))
        self.treeMemory.headerItem().setText(3, _translate("MainWindow", "Permission", None))
        self.dockWidget_3.setWindowTitle(_translate("MainWindow", "Registers", None))
        self.label.setText(_translate("MainWindow", "X0", None))
        self.label_2.setText(_translate("MainWindow", "X2", None))
        self.label_3.setText(_translate("MainWindow", "X4", None))
        self.label_4.setText(_translate("MainWindow", "X6", None))
        self.label_5.setText(_translate("MainWindow", "X8", None))
        self.label_6.setText(_translate("MainWindow", "X10", None))
        self.label_7.setText(_translate("MainWindow", "X12", None))
        self.label_8.setText(_translate("MainWindow", "X14", None))
        self.label_9.setText(_translate("MainWindow", "X16", None))
        self.label_10.setText(_translate("MainWindow", "X18", None))
        self.label_11.setText(_translate("MainWindow", "X20", None))
        self.label_12.setText(_translate("MainWindow", "X22", None))
        self.label_13.setText(_translate("MainWindow", "X24", None))
        self.label_14.setText(_translate("MainWindow", "X26", None))
        self.label_15.setText(_translate("MainWindow", "X28", None))
        self.label_16.setText(_translate("MainWindow", "LR", None))
        self.label_33.setText(_translate("MainWindow", "SP", None))
        self.label_17.setText(_translate("MainWindow", "X1", None))
        self.label_18.setText(_translate("MainWindow", "X3", None))
        self.label_19.setText(_translate("MainWindow", "X5", None))
        self.label_20.setText(_translate("MainWindow", "X7", None))
        self.label_21.setText(_translate("MainWindow", "X9", None))
        self.label_22.setText(_translate("MainWindow", "X11", None))
        self.label_23.setText(_translate("MainWindow", "X13", None))
        self.label_24.setText(_translate("MainWindow", "X15", None))
        self.label_25.setText(_translate("MainWindow", "X17", None))
        self.label_26.setText(_translate("MainWindow", "X19", None))
        self.label_27.setText(_translate("MainWindow", "X21", None))
        self.label_28.setText(_translate("MainWindow", "X23", None))
        self.label_29.setText(_translate("MainWindow", "X25", None))
        self.label_30.setText(_translate("MainWindow", "X27", None))
        self.label_31.setText(_translate("MainWindow", "X29", None))
        self.label_32.setText(_translate("MainWindow", "PC", None))
        self.dockWidget_4.setWindowTitle(_translate("MainWindow", "Thread List", None))
        self.treeThreads.headerItem().setText(0, _translate("MainWindow", "ID", None))
        self.treeThreads.headerItem().setText(1, _translate("MainWindow", "Entrypoint", None))
        self.treeThreads.headerItem().setText(2, _translate("MainWindow", "LocalStorage", None))
        self.dockWidget_5.setWindowTitle(_translate("MainWindow", "Breakpoints", None))
        self.treeBreakpoints.headerItem().setText(0, _translate("MainWindow", "Address", None))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Stack Trace", None))
        self.dockWidget_6.setWindowTitle(_translate("MainWindow", "View #0", None))
        self.dockWidget_7.setWindowTitle(_translate("MainWindow", "View #1", None))
        self.dockWidget_8.setWindowTitle(_translate("MainWindow", "View #2", None))

